-- 코드를 입력하세요
SELECT A.FLAVOR
FROM (SELECT * FROM FIRST_HALF WHERE TOTAL_ORDER > 3000) AS A
JOIN ICECREAM_INFO AS B ON A.FLAVOR = B.FLAVOR
WHERE B.INGREDIENT_TYPE = "FRUIT_BASED"
ORDER BY TOTAL_ORDER DESC;