-- 코드를 입력하세요
SELECT C.CAR_ID, C.CAR_TYPE, (C.DAILY_FEE * 30 * (100 - D.DISCOUNT_RATE) / 100) AS FEE
FROM (SELECT A.CAR_ID, A.CAR_TYPE, A.DAILY_FEE FROM CAR_RENTAL_COMPANY_CAR AS A WHERE A.CAR_TYPE REGEXP 'SUV|세단' AND A.CAR_ID NOT IN (SELECT DISTINCT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01')) AS C
JOIN (SELECT CAR_TYPE, DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE = "30일 이상") AS D ON C.CAR_TYPE = D.CAR_TYPE
WHERE (C.DAILY_FEE * 30 * (100 - D.DISCOUNT_RATE) / 100) BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;