-- 코드를 입력하세요
SELECT A.HISTORY_ID, (A.DAILY_FEE * A.DURATION * (100 - IFNULL(B.DISCOUNT_RATE, 0)) / 100) AS FEE
FROM (SELECT A.HISTORY_ID, B.CAR_TYPE, B.DAILY_FEE, DATEDIFF(A.END_DATE, A.START_DATE) + 1 AS DURATION FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A JOIN (SELECT * FROM CAR_RENTAL_COMPANY_CAR WHERE CAR_TYPE = '트럭') AS B ON A.CAR_ID = B.CAR_ID) AS A
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS B ON A.CAR_TYPE = B.CAR_TYPE AND ((A.DURATION >= 7 AND A.DURATION < 30 AND B.DURATION_TYPE = '7일 이상') OR (A.DURATION >= 30 AND A.DURATION < 90 AND B.DURATION_TYPE = '30일 이상') OR (A.DURATION >= 90 AND B.DURATION_TYPE = '90일 이상'))
ORDER BY FEE DESC, A.HISTORY_ID DESC;