SELECT A.CATEGORY, SUM(B.SALES) AS TOTAL_SALES
FROM BOOK AS A
JOIN (SELECT BOOK_ID, SALES FROM BOOK_SALES WHERE SALES_DATE >= "2022-01-01" AND SALES_DATE <= "2022-01-31") AS B ON A.BOOK_ID = B.BOOK_ID
GROUP BY A.CATEGORY
ORDER BY CATEGORY;